# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
# success_symbol = "[](bold green)[](bold yellow)[](bold red)[](bold purple)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
success_symbol = "[](bold dimmed white)[](bold white)[](bold magenta)[󰅂](bold blue)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

error_symbol = "[](bold dimmed white)[](bold white)[](bold magenta)[](bold red)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
symbol = " " # nf-oct-git_branch
truncation_length = 4
truncation_symbol = ""
style = "bold megenta"

[git_commit]
commit_hash_length = 4
tag_symbol = " " # nf-fa-tag

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ PICKING](bold red)" # nf-seti-cherry

[git_status]
conflicted = ""        # nf-dev-git_merge
ahead = " "            # nf-fa-arrow_up
behind = " "           # nf-fa-arrow_down
diverged = "󰨁 "         # nf-mdi-map_legend (for diverged)
untracked = ""        # nf-fa-question_circle
stashed = "󰆼 "          # nf-mdi-database (symbolic for stash)
modified = " "         # nf-oct-pencil
staged = '[\($count\)](green)'  # nf-fa-plus_circle
renamed = " "          # nf-oct-file_symlink_file
deleted = " "          # nf-fa-trash
style = "bold purple"

[hostname]
ssh_only = false
format =  "on [Karakura](bold cyan) " # nf-cod-server
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " " # nf-mdi-memory
style = "bold dimmed green"

[time]
disabled = true
format = ' [\[$time\]]($style) ' # nf-fa-clock_o
time_format = "%T"

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

[directory]
style = "bold blue"
truncation_length = 2
truncation_symbol = "./"